sudo: true
language: android
dist: trusty
install: true
jdk:
- oraclejdk8
branches:
  only:
  - master
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-29.0.1
  - android-29
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  = chmod +x gradlew
  - yes | sdkmanager "platforms;android-29"
script: 
  - ./gradlew -S clean build 
